### ISSUE TITLE
Cannot read .rds files

### ISSUE THREAD

**Issue by kelvinyevng** [ChengLabGit/RashX_optimized#1]
Hi,

I am trying to play around with your tool. But it doesnt seem to work.

Rashx::process_requests(rds1 = "/file/path/.rds", plot1_name = "plot1", plot2_name = "plot2", plot3_name = "plot3", plot4_name = "plot4", exported_file_name = "example.csv", original_file_name = "testrun")

Error in readRDS(data_file_path) : unknown input format

**Comment by caeser1996** [comment]
Hey,
Ken which branch you are in ?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: kelvinyevng ***@***.***>
Sent: Thursday, December 7, 2023 1:51:47 AM
To: ChengLabGit/RashX_optimized ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ChengLabGit/RashX_optimized] Cannot read .rds files (Issue #1)


Hi,

I am trying to play around with your tool. But it doesnt seem to work.

Rashx::process_requests(rds1 = "/file/path/.rds", plot1_name = "plot1", plot2_name = "plot2", plot3_name = "plot3", plot4_name = "plot4", exported_file_name = "example.csv", original_file_name = "testrun")

Error in readRDS(data_file_path) : unknown input format

**Comment by kelvinyevng** [comment]
Package: Rashx
Type: Package
Title: What the Package Does (Title Case)
Version: 0.1.0
Author: Who wrote it
Maintainer: Sumanta Mukhopadhyay <sumanta9090@gmail.com>
Description: More about what it does (maybe more than one line) Use four spaces when indenting
           paragraphs within the Description.
License: What license is it under?
Encoding: UTF-8
LazyData: true
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: RashX_optimized
RemoteUsername: ChengLabGit
RemoteRef: HEAD
RemoteSha: dee6af26449ccee3ad9782cf9f1b20a0c5cf393b
GithubRepo: RashX_optimized
GithubUsername: ChengLabGit
GithubRef: HEAD
GithubSHA1: dee6af26449ccee3ad9782cf9f1b20a0c5cf393b
NeedsCompilation: no
Packaged: 2023-12-06 19:46:30 UTC; qph762
Built: R 4.1.3; ; 2023-12-06 19:46:30 UTC; unix

**Comment by caeser1996** [comment]
process_requests(rds1, exported_file_name, plot1_name, plot2_name, plot3_name, plot4_name, original_file_name)

Please pass the correct rds file and see 
"/file/path/.rds"

What is the rds file?
@kelvinyevng

**Comment by kelvinyevng** [comment]
Can you show me an example of executing your command? 
I would just pass the file path as with the readRDS() function.
But it doesnt work with your process_requests()
rds1 = "~/Downloads/skin276.rds"

**Comment by caeser1996** [comment]
Let me do the same I will post you the command

**Comment by caeser1996** [comment]
@kelvinyevng  we have generated a ticket for the same.We will get back to you as soon as it is resolved.

**Comment by kelvinyevng** [comment]
Oh alright. Glad to hear, looking forward to trying your model.

**Comment by caeser1996** [comment]
install.packages("remotes")
install.packages("devtools")
devtools::install_github('cole-trapnell-lab/monocle3')
remotes::install_github("https://github.com/ChengLabGit/RashX_optimized.git")

Download the model_file from : https://assetsdemo.s3.us-east-2.amazonaws.com/skin_integrated.rds

process_requests(model_file_path,rds1, exported_file_name, plot1_name, plot2_name, plot3_name, plot4_name, original_file_name)

@kelvinyevng
